export const pluginSourceCode = [
  '<?php',
  '/**',
  ' * Plugin Name: Dev-Console Connector',
  ' * Description: Securely connects your WordPress site to the Dev-Console Co-Pilot application.',
  ' * Version: 2.4.0',
  ' * Author: PM-SHRI',
  ' * Author URI: https://ponsrischool.in',
  ' */',
  '',
  'if (!defined(\'ABSPATH\')) {',
  '    exit;',
  '}',
  '',
  'define(\'DC_CONNECTOR_KEY_OPTION\', \'dc_connector_key\');',
  'define(\'DC_API_KEY_OPTION\', \'dc_api_key\');',
  'define(\'DC_CORS_SETTINGS_OPTION\', \'dc_connector_cors_settings\');',
  'define(\'DC_BACKUP_DIR_FILES\', \'dev-console-backups/file-history\');',
  'define(\'DC_BACKUP_DIR_SITE\', \'dev-console-backups/site-backups\');',
  '',
  'class Dev_Console_Connector {',
  '',
  '    private static $instance;',
  '',
  '    public static function get_instance() {',
  '        if (null === self::$instance) {',
  '            self::$instance = new self();',
  '        }',
  '        return self::$instance;',
  '    }',
  '',
  '    private function __construct() {',
  '        add_action(\'rest_api_init\', [$this, \'register_routes\']);',
  '        add_action(\'admin_menu\', [$this, \'add_admin_menu\']);',
  '        add_filter(\'rest_pre_serve_request\', [$this, \'handle_cors_headers\'], 10, 4);',
  '    }',
  '',
  '    public function activate() {',
  '        if (!get_option(DC_CONNECTOR_KEY_OPTION)) { update_option(DC_CONNECTOR_KEY_OPTION, wp_generate_password(64, false, false)); }',
  '        if (!get_option(DC_API_KEY_OPTION)) { update_option(DC_API_KEY_OPTION, wp_generate_password(64, false, false)); }',
  '        if (!get_option(DC_CORS_SETTINGS_OPTION)) { add_option(DC_CORS_SETTINGS_OPTION, [\'allow_all\' => false, \'allowed_origins\' => \'dev.ponsrischool.in\']); }',
  '    }',
  '',
  '    public function add_admin_menu() {',
  '        add_menu_page(\'Dev-Console Connector\', \'Connector\', \'manage_options\', \'dev-console-connector\', [$this, \'create_settings_page_html\'], \'dashicons-admin-plugins\');',
  '    }',
  '',
  '    public function create_settings_page_html() {',
  '        ?>',
  '        <div class="wrap">',
  '            <h1>Dev-Console Connector Settings</h1>',
  '            <p>Use the details below to connect your Dev-Console application to this WordPress site.</p>',
  '',
  '            <h2>Connection Keys</h2>',
  '            <p>Copy these keys into the connection modal in the Dev-Console application.</p>',
  '            <table class="form-table" role="presentation">',
  '                <tbody>',
  '                    <tr>',
  '                        <th scope="row"><label for="dc_connector_key">Connector Key</label></th>',
  '                        <td>',
  '                            <input type="text" id="dc_connector_key" readonly value="<?php echo esc_attr(get_option(DC_CONNECTOR_KEY_OPTION)); ?>" class="regular-text" />',
  '                            <button type="button" class="button button-secondary" onclick="copyToClipboard(\'dc_connector_key\')">Copy</button>',
  '                        </td>',
  '                    </tr>',
  '                    <tr>',
  '                        <th scope="row"><label for="dc_api_key">API Key</label></th>',
  '                        <td>',
  '                            <input type="text" id="dc_api_key" readonly value="<?php echo esc_attr(get_option(DC_API_KEY_OPTION)); ?>" class="regular-text" />',
  '                             <button type="button" class="button button-secondary" onclick="copyToClipboard(\'dc_api_key\')">Copy</button>',
  '                        </td>',
  '                    </tr>',
  '                </tbody>',
  '            </table>',
  '            ',
  '            <hr/>',
  '',
  '            <div id="dc-connector-settings-form">',
  '                <?php',
  '                $options = get_option(DC_CORS_SETTINGS_OPTION, [\'allow_all\' => false, \'allowed_origins\' => \'dev.ponsrischool.in\']);',
  '                ?>',
  '                <h2>Security: Allowed Origins (CORS)</h2>',
  '                <p>Control which frontend domains can access this site\\\'s Connector API.</p>',
  '                <table class="form-table" role="presentation">',
  '                    <tbody>',
  '                         <tr>',
  '                            <th scope="row">Allow All Origins</th>',
  '                            <td>',
  '                                <input type="checkbox" id="dc_connector_allow_all" name="allow_all" <?php checked(isset($options[\'allow_all\']) && $options[\'allow_all\'], true); ?> />',
  '                                <p class="description"><strong>Warning:</strong> For development use only. Allows any domain to make requests.</p>',
  '                            </td>',
  '                        </tr>',
  '                        <tr>',
  '                            <th scope="row"><label for="dc_connector_allowed_origins">Allowed Origins</label></th>',
  '                            <td>',
  '                                <textarea name="allowed_origins" rows="5" cols="50" class="large-text" id="dc_connector_allowed_origins"><?php echo esc_textarea($options[\'allowed_origins\'] ?? \'\'); ?></textarea>',
  '                                <p class="description">Enter allowed domains, one per line (e.g., https://dev.ponsrischool.in, http://localhost:5173).</p>',
  '                            </td>',
  '                        </tr>',
  '                    </tbody>',
  '                </table>',
  '                <p class="submit">',
  '                    <button type="button" id="dc-save-connector-settings" class="button button-primary">Save CORS Settings</button>',
  '                    <span id="dc-connector-spinner" class="spinner" style="float: none; vertical-align: middle; margin-left: 10px;"></span>',
  '                    <span id="dc-connector-feedback" style="margin-left: 10px; vertical-align: middle;"></span>',
  '                </p>',
  '            </div>',
  '        </div>',
  '        <script>',
  '            function copyToClipboard(elementId) {',
  '                var copyText = document.getElementById(elementId);',
  '                copyText.select();',
  '                copyText.setSelectionRange(0, 99999); /* For mobile devices */',
  '                document.execCommand("copy");',
  '                alert("Copied the key!");',
  '            }',
  '',
  '            document.addEventListener(\'DOMContentLoaded\', function() {',
  '                const allowAllCheckbox = document.getElementById(\'dc_connector_allow_all\');',
  '                const originsTextarea = document.getElementById(\'dc_connector_allowed_origins\');',
  '                const saveBtn = document.getElementById(\'dc-save-connector-settings\');',
  '                const spinner = document.getElementById(\'dc-connector-spinner\');',
  '                const feedback = document.getElementById(\'dc-connector-feedback\');',
  '',
  '                const toggleTextarea = () => {',
  '                    if (originsTextarea && allowAllCheckbox) {',
  '                        originsTextarea.disabled = allowAllCheckbox.checked;',
  '                        originsTextarea.closest(\'tr\').style.opacity = allowAllCheckbox.checked ? 0.6 : 1;',
  '                    }',
  '                };',
  '                if (allowAllCheckbox) {',
  '                    allowAllCheckbox.addEventListener(\'change\', toggleTextarea);',
  '                    toggleTextarea();',
  '                }',
  '',
  '                if (saveBtn) {',
  '                    saveBtn.addEventListener(\'click\', function() {',
  '                        spinner.style.visibility = \'visible\';',
  '                        feedback.textContent = \'\';',
  '                        saveBtn.disabled = true;',
  '',
  '                        const data = {',
  '                            allow_all: allowAllCheckbox.checked,',
  '                            allowed_origins: originsTextarea.value',
  '                        };',
  '',
  '                        fetch(\'<?php echo esc_url_raw(rest_url(\\\'dev-console/v1/connector-settings\\\')); ?>\', {',
  '                            method: \'POST\',',
  '                            headers: {',
  '                                \'Content-Type\': \'application/json\',',
  '                                \'X-WP-Nonce\': \'<?php echo wp_create_nonce(\\\'wp_rest\\\'); ?>\'',
  '                            },',
  '                            body: JSON.stringify(data)',
  '                        })',
  '                        .then(response => {',
  '                            if (!response.ok) {',
  '                               return response.json().then(err => { throw new Error(err.message || \\\'HTTP error!\\\') });',
  '                            }',
  '                            return response.json();',
  '                        })',
  '                        .then(result => {',
  '                            feedback.style.color = \'green\';',
  '                            feedback.textContent = \'Settings Saved!\';',
  '                        })',
  '                        .catch(error => {',
  '                            feedback.style.color = \'red\';',
  '                            feedback.textContent = \'Error: \' + error.message;',
  '                        })',
  '                        .finally(() => {',
  '                            spinner.style.visibility = \'hidden\';',
  '                            saveBtn.disabled = false;',
  '                            setTimeout(() => { feedback.textContent = \'\'; }, 3000);',
  '                        });',
  '                    });',
  '                }',
  '            });',
  '        </script>',
  '        <?php',
  '    }',
  '    ',
  '    public function handle_cors_headers($served, $result, $request, $server) {',
  '        $origin = get_http_origin();',
  '        if (!$origin) return $served;',
  '',
  '        $cors_options = get_option(DC_CORS_SETTINGS_OPTION, [\'allow_all\' => false, \'allowed_origins\' => \'\']);',
  '        $allowed = !empty($cors_options[\'allow_all\']);',
  '',
  '        if (!$allowed) {',
  '            $allowed_origins = array_map(\'trim\', preg_split("/[\\r\\n,]+/", $cors_options[\'allowed_origins\'] ?? \'\'));',
  '            if (in_array($origin, $allowed_origins, true)) {',
  '                $allowed = true;',
  '            }',
  '        }',
  '',
  '        if ($allowed) {',
  '            header(\'Access-Control-Allow-Origin: \' . esc_url_raw($origin));',
  '            header(\'Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE\');',
  '            header(\'Access-Control-Allow-Headers: Content-Type, X-Connector-Key, X-Api-Key, Authorization\');',
  '            if (\'OPTIONS\' === $_SERVER[\'REQUEST_METHOD\']) { status_header(200); exit(0); }',
  '        }',
  '        return $served;',
  '    }',
  '',
  '    public function register_routes() {',
  '        register_rest_route(\'dev-console/v1\', \'/execute\', [\'methods\' => \'POST\', \'callback\' => [$this, \'handle_execute\'], \'permission_callback\' => [$this, \'permission_check\']]);',
  '        register_rest_route(\'dev-console/v1\', \'/connector-settings\', [\'methods\' => \'POST\', \'callback\' => [$this, \'handle_save_connector_settings\'], \'permission_callback\' => function() { return current_user_can(\'manage_options\'); }]);',
  '    }',
  '',
  '    public function handle_save_connector_settings(WP_REST_Request $request) {',
  '        $params = $request->get_json_params();',
  '        update_option(DC_CORS_SETTINGS_OPTION, [\'allow_all\' => !empty($params[\'allow_all\']), \'allowed_origins\' => sanitize_textarea_field($params[\'allowed_origins\'] ?? \'\')]);',
  '        return new WP_REST_Response([\'success\' => true], 200);',
  '    }',
  '',
  '    public function permission_check(WP_REST_Request $request) {',
  '        $key = $request->get_header(\'X-Connector-Key\');',
  '        $api_key = $request->get_header(\'X-Api-Key\');',
  '        if (!hash_equals(get_option(DC_CONNECTOR_KEY_OPTION), $key) || !hash_equals(get_option(DC_API_KEY_OPTION), $api_key)) {',
  '            return new WP_Error(\'auth_failed\', \'Invalid credentials.\', [\'status\' => 403]);',
  '        }',
  '        return true;',
  '    }',
  '',
  '    public function handle_execute(WP_REST_Request $request) {',
  '        $params = $request->get_json_params();',
  '        $action = $params[\'action\'] ?? null;',
  '        if (!$action) { return new WP_Error(\'invalid_request\', \'No action.\', [\'status\' => 400]); }',
  '',
  '        $method = \'action_\' . $action;',
  '        if (method_exists($this, $method)) {',
  '            try {',
  '                return new WP_REST_Response([\'success\' => true, \'data\' => $this->$method($params[\'payload\'] ?? [])], 200);',
  '            } catch (Exception $e) {',
  '                return new WP_Error(\'action_failed\', $e->getMessage(), [\'status\' => 500]);',
  '            }',
  '        }',
  '        return new WP_Error(\'invalid_action\', \'Invalid action.\', [\'status\' => 400]);',
  '    }',
  '',
  '    private function get_asset_path($id, $type) { return $type === \'plugin\' ? WP_PLUGIN_DIR . \'/\' . dirname($id) : get_theme_root() . \'/\' . $id; }',
  '    ',
  '    private function backup_file($path, $id, $type, $rel_path) {',
  '        if (!file_exists($path) || !is_readable($path)) { return; }',
  '        $upload_dir = wp_upload_dir();',
  '        $backup_dir = $upload_dir[\'basedir\'] . \'/\' . DC_BACKUP_DIR_FILES . \'/\' . $type . \'/\' . dirname($id) . \'/\' . dirname($rel_path);',
  '        wp_mkdir_p($backup_dir);',
  '        $backup_path = $backup_dir . \'/\' . basename($rel_path) . \'.\' . time() . \'.bak\';',
  '        copy($path, $backup_path);',
  '    }',
  '',
  '    private function resolve_path($id, $type, $rel_path) {',
  '        $base = ($id === \'root\') ? ABSPATH : $this->get_asset_path($id, $type);',
  '        $path = $base . \'/\' . $rel_path;',
  '        ',
  '        $real_base = realpath($base);',
  '        $real_path = realpath($path);',
  '',
  '        if ($real_path === false || strpos($real_path, $real_base) !== 0) { throw new Exception(\'Invalid file path or directory traversal.\'); }',
  '        if ($id === \'root\' && in_array(basename($path), [\'wp-config.php\', \'.htaccess\'])) { throw new Exception(\'Editing this sensitive file is not permitted.\'); }',
  '        ',
  '        return $path;',
  '    }',
  '',
  '    private function action_get_db_tables($payload) {',
  '        global $wpdb;',
  '        return $wpdb->get_col("SHOW TABLES");',
  '    }',
  '',
  '    private function action_get_asset_files($payload) {',
  '        $base_path = ($payload[\'assetIdentifier\'] === \'root\') ? ABSPATH : $this->get_asset_path($payload[\'assetIdentifier\'], $payload[\'assetType\']);',
  '        $files = [];',
  '        $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($base_path, FilesystemIterator::SKIP_DOTS | FilesystemIterator::UNIX_PATHS), RecursiveIteratorIterator::SELF_FIRST);',
  '        $exclusions = [\'wp-admin\', \'wp-includes\', \'.git\', \'.github\', \'.vscode\', \'node_modules\', \'vendor\', \'wp-content/uploads\', \'wp-content/cache\', \'wp-content/upgrade\', \'wp-config.php\', \'.htaccess\', \'license.txt\', \'readme.html\'];',
  '        $exclude_patterns = array_map(function($item) use ($base_path) { return \'#^\' . preg_quote($base_path . $item, \'#\') . \'#\'; }, $exclusions);',
  '',
  '        foreach ($iterator as $file) {',
  '            if ($payload[\'assetIdentifier\'] === \'root\') {',
  '                $is_excluded = false;',
  '                foreach ($exclude_patterns as $pattern) { if (preg_match($pattern, $file->getPathname())) { $is_excluded = true; break; } }',
  '                if ($is_excluded) continue;',
  '            }',
  '            if ($file->isFile()) { $files[] = [\'name\' => ltrim(str_replace($base_path, \'\', $file->getPathname()), \'/\')]; }',
  '        }',
  '        usort($files, fn($a, $b) => strcmp($a[\'name\'], $b[\'name\']));',
  '        return $files;',
  '    }',
  '',
  '    private function action_read_file_content($payload) {',
  '        $upload_dir = wp_upload_dir();',
  '        $backup_base_dir = realpath($upload_dir[\'basedir\'] . \'/\' . DC_BACKUP_DIR_FILES);',
  '        $is_backup_read = strpos($payload[\'relativePath\'], DC_BACKUP_DIR_FILES) !== false;',
  '',
  '        if ($is_backup_read && $backup_base_dir) {',
  '            $path = realpath($payload[\'relativePath\']);',
  '            if ($path === false || strpos($path, $backup_base_dir) !== 0) {',
  '                throw new Exception(\'Invalid backup file path.\');',
  '            }',
  '        } else {',
  '            $path = $this->resolve_path($payload[\'assetIdentifier\'], $payload[\'assetType\'], $payload[\'relativePath\']);',
  '        }',
  '',
  '        if (!is_readable($path)) throw new Exception(\'File not found or not readable.\');',
  '        return [\'content\' => file_get_contents($path)];',
  '    }',
  '',
  '    private function action_write_file_content($payload) {',
  '        global $wp_filesystem;',
  '        WP_Filesystem();',
  '        $path = $this->resolve_path($payload[\'assetIdentifier\'], $payload[\'assetType\'], $payload[\'relativePath\']);',
  '        if (file_exists($path)) { $this->backup_file($path, $payload[\'assetIdentifier\'], $payload[\'assetType\'], $payload[\'relativePath\']); }',
  '        if (!$wp_filesystem->put_contents($path, $payload[\'content\'], FS_CHMOD_FILE)) { throw new Exception(\'Failed to write file.\'); }',
  '        return [\'status\' => \'ok\'];',
  '    }',
  '',
  '    private function action_create_site_backup($payload) {',
  '        // Limited to wp-content for safety/performance.',
  '        $source_dir = WP_CONTENT_DIR;',
  '        $upload_dir = wp_upload_dir();',
  '        $backup_dir = $upload_dir[\'basedir\'] . \'/\' . DC_BACKUP_DIR_SITE;',
  '        wp_mkdir_p($backup_dir);',
  '        ',
  '        $file_name = \'site-backup-\' . date(\'Y-m-d-H-i-s\') . \'.zip\';',
  '        $zip_path = $backup_dir . \'/\' . $file_name;',
  '',
  '        $zip = new ZipArchive();',
  '        if ($zip->open($zip_path, ZipArchive::CREATE) !== TRUE) { throw new Exception(\'Cannot create backup zip file.\'); }',
  '        ',
  '        $files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($source_dir), RecursiveIteratorIterator::LEAVES_ONLY);',
  '        foreach ($files as $name => $file) {',
  '            if (!$file->isDir()) {',
  '                $filePath = $file->getRealPath();',
  '                $relativePath = substr($filePath, strlen($source_dir) + 1);',
  '                $zip->addFile($filePath, $relativePath);',
  '            }',
  '        }',
  '        $zip->close();',
  '        ',
  '        $content = file_get_contents($zip_path);',
  '        unlink($zip_path); // Clean up immediately after reading',
  '        return [\'status\' => \'ok\', \'fileName\' => $file_name, \'content\' => base64_encode($content)];',
  '    }',
  '',
  '    private function action_update_plugin_file($payload) {',
  '        global $wp_filesystem;',
  '        WP_Filesystem();',
  '',
  '        $path = ($payload[\'plugin_type\'] === \'connector\') ? __FILE__ : WP_PLUGIN_DIR . \'/dev-console-master-controller/dev-console-master-controller.php\';',
  '        if (!file_exists($path)) { throw new Exception(\'Target plugin file not found.\'); }',
  '        ',
  '        copy($path, $path . \'.bak\');',
  '        if (!$wp_filesystem->put_contents($path, $payload[\'content\'], FS_CHMOD_FILE)) {',
  '            copy($path . \'.bak\', $path); // Rollback',
  '            throw new Exception(\'Failed to update plugin file.\');',
  '        }',
  '        unlink($path . \'.bak\');',
  '        return [\'status\' => \'ok\', \'message\' => ucfirst($payload[\'plugin_type\']) . \' plugin updated.\'];',
  '    }',
  '',
  '    private function action_ping($payload) {',
  '        if (!function_exists(\'get_plugin_data\')) { require_once ABSPATH . \'wp-admin/includes/plugin.php\'; }',
  '        $plugin_data = get_plugin_data(__FILE__);',
  '        return [',
  '            \'message\' => \'pong\',',
  '            \'connector_version\' => $plugin_data[\'Version\']',
  '        ];',
  '    }',
  '',
  '    private function action_list_assets($payload) {',
  '        $asset_type = $payload[\'assetType\'];',
  '        $results = [];',
  '        if ($asset_type === \'plugin\') {',
  '            if (!function_exists(\'get_plugins\')) { require_once ABSPATH . \'wp-admin/includes/plugin.php\'; }',
  '            $all_plugins = get_plugins();',
  '            $active_plugins = get_option(\'active_plugins\');',
  '            foreach ($all_plugins as $path => $details) {',
  '                $results[] = [',
  '                    \'type\' => \'plugin\',',
  '                    \'name\' => $details[\'Name\'],',
  '                    \'identifier\' => $path,',
  '                    \'version\' => $details[\'Version\'],',
  '                    \'isActive\' => in_array($path, $active_plugins)',
  '                ];',
  '            }',
  '        } else { // theme',
  '            $all_themes = wp_get_themes();',
  '            $active_theme = get_stylesheet();',
  '            foreach ($all_themes as $slug => $theme) {',
  '                $results[] = [',
  '                    \'type\' => \'theme\',',
  '                    \'name\' => $theme->get(\'Name\'),',
  '                    \'identifier\' => $slug,',
  '                    \'version\' => $theme->get(\'Version\'),',
  '                    \'isActive\' => $slug === $active_theme',
  '                ];',
  '            }',
  '        }',
  '        return $results;',
  '    }',
  '',
  '    private function action_toggle_asset_status($payload) {',
  '        $asset_type = $payload[\'assetType\'];',
  '        $id = $payload[\'assetIdentifier\'];',
  '        $new_status = $payload[\'newStatus\'];',
  '',
  '        if ($asset_type === \'plugin\') {',
  '            if (!function_exists(\'activate_plugin\') || !function_exists(\'deactivate_plugins\')) { require_once ABSPATH . \'wp-admin/includes/plugin.php\'; }',
  '            if ($new_status) {',
  '                activate_plugin($id);',
  '            } else {',
  '                deactivate_plugins($id);',
  '            }',
  '        } else { // theme',
  '            if ($new_status) {',
  '                switch_theme($id);',
  '            } else {',
  '                throw new Exception(\'Cannot deactivate the active theme. Switch to another theme to deactivate this one.\');',
  '            }',
  '        }',
  '        return [\'status\' => \'ok\'];',
  '    }',
  '',
  '    private function action_delete_asset($payload) {',
  '        require_once ABSPATH . \'wp-admin/includes/file.php\';',
  '        $asset_type = $payload[\'assetType\'];',
  '        $id = $payload[\'assetIdentifier\'];',
  '',
  '        if ($asset_type === \'plugin\') {',
  '            if (!function_exists(\'delete_plugins\')) { require_once ABSPATH . \'wp-admin/includes/plugin.php\'; }',
  '            $result = delete_plugins([$id]);',
  '             if (is_wp_error($result)) { throw new Exception($result->get_error_message()); }',
  '        } else {',
  '            if (!function_exists(\'delete_theme\')) { require_once ABSPATH . \'wp-admin/includes/theme.php\'; }',
  '            $result = delete_theme($id);',
  '             if (is_wp_error($result)) { throw new Exception($result->get_error_message()); }',
  '        }',
  '        return [\'status\' => \'ok\'];',
  '    }',
  '',
  '    private function action_install_asset($payload) {',
  '        global $wp_filesystem;',
  '        WP_Filesystem();',
  '',
  '        $asset_type = $payload[\'assetType\'];',
  '        $asset_name_slug = sanitize_file_name($payload[\'assetName\']);',
  '        $files = $payload[\'files\'];',
  '        $base_path = ($asset_type === \'plugin\') ? WP_PLUGIN_DIR : get_theme_root();',
  '        $asset_dir = $base_path . \'/\' . $asset_name_slug;',
  '',
  '        if ($wp_filesystem->exists($asset_dir)) {',
  '            throw new Exception(ucfirst($asset_type) . \' folder already exists.\');',
  '        }',
  '        $wp_filesystem->mkdir($asset_dir);',
  '',
  '        foreach ($files as $file) {',
  '            $path = $asset_dir . \'/\' . $file[\'name\'];',
  '            $dir = dirname($path);',
  '            if (!$wp_filesystem->exists($dir)) {',
  '                $wp_filesystem->mkdir($dir, FS_CHMOD_DIR);',
  '            }',
  '            if (!$wp_filesystem->put_contents($path, base64_decode($file[\'content\']), FS_CHMOD_FILE)) {',
  '                throw new Exception(\'Failed to write file: \' . $file[\'name\']);',
  '            }',
  '        }',
  '        return [\'status\' => \'ok\'];',
  '    }',
  '    ',
  '    private function action_get_file_history($payload) {',
  '        $upload_dir = wp_upload_dir();',
  '        $backup_dir = $upload_dir[\'basedir\'] . \'/\' . DC_BACKUP_DIR_FILES . \'/\' . $payload[\'assetType\'] . \'/\' . dirname($payload[\'assetIdentifier\']) . \'/\' . dirname($payload[\'relativePath\']);',
  '        if (!is_dir($backup_dir)) return [];',
  '        ',
  '        $files = scandir($backup_dir);',
  '        $backups = [];',
  '        foreach ($files as $file) {',
  '            if (strpos($file, basename($payload[\'relativePath\'])) === 0 && strpos($file, \'.bak\') !== false) {',
  '                 $parts = explode(\'.\', $file);',
  '                 $timestamp = $parts[count($parts) - 2];',
  '                 $backups[] = [\'path\' => $backup_dir . \'/\' . $file, \'timestamp\' => $timestamp];',
  '            }',
  '        }',
  '        rsort($backups);',
  '        return $backups;',
  '    }',
  '',
  '    private function action_restore_file($payload) {',
  '        global $wp_filesystem;',
  '        WP_Filesystem();',
  '        $target_path = $this->resolve_path($payload[\'assetIdentifier\'], $payload[\'assetType\'], $payload[\'relativePath\']);',
  '        $backup_path = $payload[\'backupPath\'];',
  '',
  '        $upload_dir = wp_upload_dir();',
  '        if (strpos(realpath($backup_path), realpath($upload_dir[\'basedir\'])) !== 0) {',
  '            throw new Exception(\'Invalid backup path.\');',
  '        }',
  '',
  '        if (!file_exists($backup_path)) { throw new Exception(\'Backup file not found.\'); }',
  '        ',
  '        $this->backup_file($target_path, $payload[\'assetIdentifier\'], $payload[\'assetType\'], $payload[\'relativePath\']);',
  '        ',
  '        if (!$wp_filesystem->copy($backup_path, $target_path, true)) {',
  '            throw new Exception(\'Failed to restore file.\');',
  '        }',
  '        return [\'status\' => \'ok\'];',
  '    }',
  '',
  '    private function action_execute_safe_db_query($payload) {',
  '        global $wpdb;',
  '        $queryType = $payload[\'queryType\'];',
  '        $params = $payload[\'params\'] ?? [];',
  '',
  '        switch ($queryType) {',
  '            case \'get_options\':',
  '                $optionNames = $params[\'optionNames\'] ?? [];',
  '                if (empty($optionNames)) return [];',
  '                $placeholders = implode(\', \', array_fill(0, count($optionNames), \'%s\'));',
  '                return $wpdb->get_results($wpdb->prepare("SELECT option_name, option_value FROM {$wpdb->options} WHERE option_name IN ($placeholders)", ...$optionNames), ARRAY_A);',
  '            case \'list_posts\':',
  '                $post_type = $params[\'postType\'] ?? \'post\';',
  '                $limit = isset($params[\'limit\']) ? intval($params[\'limit\']) : 10;',
  '                $offset = isset($params[\'offset\']) ? intval($params[\'offset\']) : 0;',
  '                 return get_posts([\'post_type\' => $post_type, \'numberposts\' => $limit, \'offset\' => $offset, \'post_status\' => \'any\']);',
  '            default:',
  '                throw new Exception("Unsupported query type.");',
  '        }',
  '    }',
  '',
  '    private function action_run_security_scan($payload) {',
  '        global $wpdb;',
  '        $results = [];',
  '        $results[] = [\'id\' => \'wp_debug\', \'title\' => \'WP_DEBUG is Disabled on Live Site\', \'status\' => (defined(\'WP_DEBUG\') && WP_DEBUG) ? \'fail\' : \'pass\', \'severity\' => \'High\', \'description\' => \'WP_DEBUG should be turned off on a live website as it can expose sensitive information.\', \'recommendation\' => \'Set WP_DEBUG to false in your wp-config.php file for production environments.\'];',
  '        $response = wp_remote_get(get_site_url() . \'/wp-includes/\');',
  '        $body = wp_remote_retrieve_body($response);',
  '        $results[] = [\'id\' => \'dir_listing\', \'title\' => \'Directory Listing is Disabled\', \'status\' => (strpos($body, \'<title>Index of\') !== false) ? \'fail\' : \'pass\', \'severity\' => \'Medium\', \'description\' => \'Directory listing can reveal sensitive file names to attackers.\', \'recommendation\' => \'Add "Options -Indexes" to your .htaccess file to disable directory browsing.\'];',
  '        $admin_user = get_user_by(\'login\', \'admin\');',
  '        $results[] = [\'id\' => \'default_admin\', \'title\' => \'Default "admin" User Does Not Exist\', \'status\' => $admin_user ? \'fail\' : \'pass\', \'severity\' => \'High\', \'description\' => \'Using the default "admin" username makes brute-force attacks easier.\', \'recommendation\' => \'Create a new administrator account with a unique username and delete the default "admin" account.\'];',
  '        $results[] = [\'id\' => \'file_edit\', \'title\' => \'File Editing is Disabled in wp-admin\', \'status\' => (defined(\'DISALLOW_FILE_EDIT\') && DISALLOW_FILE_EDIT) ? \'pass\' : \'warn\', \'severity\' => \'Medium\', \'description\' => \'Allowing file editing from the WordPress admin can be a security risk if an admin account is compromised.\', \'recommendation\' => \'Add `define(\\\'DISALLOW_FILE_EDIT\\\', true);` to your wp-config.php file.\'];',
  '        $results[] = [\'id\' => \'db_prefix\', \'title\' => \'Database Prefix is Not Default\', \'status\' => ($wpdb->prefix === \'wp_\') ? \'fail\' : \'pass\', \'severity\' => \'Medium\', \'description\' => \'Using the default "wp_" database prefix makes SQL injection attacks easier.\', \'recommendation\' => \'Use a unique database prefix. This requires a more involved process to change on an existing site.\'];',
  '',
  '        return $results;',
  '    }',
  '',
  '    private function action_get_debug_log($payload) {',
  '        $log_path = WP_CONTENT_DIR . \'/debug.log\';',
  '        if (!file_exists($log_path) || !is_readable($log_path)) {',
  '            throw new Exception(\'debug.log file does not exist or is not readable.\');',
  '        }',
  '        return [\'content\' => file_get_contents($log_path)];',
  '    }',
  '',
  '    private function action_list_site_backups($payload) {',
  '        $upload_dir = wp_upload_dir();',
  '        $backup_dir = $upload_dir[\'basedir\'] . \'/\' . DC_BACKUP_DIR_SITE;',
  '        if (!is_dir($backup_dir)) return [];',
  '',
  '        $files = scandir($backup_dir);',
  '        $backups = [];',
  '        foreach ($files as $file) {',
  '            if (pathinfo($file, PATHINFO_EXTENSION) === \'zip\') {',
  '                $filepath = $backup_dir . \'/\' . $file;',
  '                $backups[] = [',
  '                    \'name\' => $file,',
  '                    \'size\' => filesize($filepath),',
  '                    \'date\' => filemtime($filepath)',
  '                ];',
  '            }',
  '        }',
  '        usort($backups, fn($a, $b) => $b[\'date\'] - $a[\'date\']);',
  '        return $backups;',
  '    }',
  '}',
  '',
  '// Register activation hook correctly, outside of the class constructor.',
  'register_activation_hook(__FILE__, function() {',
  '    Dev_Console_Connector::get_instance()->activate();',
  '});',
  '',
  '// Initialize the plugin.',
  'Dev_Console_Connector::get_instance();',
].join('\n');